# Name of the workflow
name: 'Release'
# pre-release releases
on:
  release:
    types: [published]
    branches:
      - main
  workflow_dispatch: null

# Automated Jobs
jobs:
  crete_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: echo message
        run: echo "Hey Running on publish"
#       - name: Create a release branch
#         run: git checkout -b release/${{github.ref_name}}
#       - name: Push new branch
#         run: git push origin release/${{github.ref_name}}
      
